{% set name = "kthread" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kthread-{{ version }}.tar.gz
  sha256: 90e194e6a7ff903040c4133d3ea9037c908c4296bf5f582c7fdcf6325a04f9b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - nose
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - kthread
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/munshigroup/kthread
  summary: Killable threads in Python!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
